version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    ports:
      - "3306:3306" # Exposes MySQL on localhost:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Set the root password
      MYSQL_DATABASE: dev_db             # Create a default database
      MYSQL_USER: dev_user               # Create a user
      MYSQL_PASSWORD: dev_password       # Set the user's password
    volumes:
      - mysql_data:/var/lib/mysql # Attach the named volume for persistent storage
    networks: # network is optional, chat gpt says this is for code organization purposes
      - dev-network

volumes:
  mysql_data: # you have to declare all named volumes here

networks:
  dev-network:
    driver: bridge



# run this by: $ docker-compose up -d (-d = run in detached mode)
# remove by: $ docker-compose down -v (-v = delete volumes too)